combine_control_expr = false
comment_width = 100
condense_wildcard_suffixes = true
force_multiline_blocks = true
match_arm_blocks = false
match_block_trailing_comma = true
max_width = 100
merge_imports = true
reorder_impl_items = true
report_todo = "Always"
report_fixme = "Always"
trailing_semicolon = false
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true